// Journey: 48 authored stages in 6 chapters (mechanics introduced in
// isolation, combined with known ones, then a mastery stage per chapter).
// Plus 8 challenge stages with constrained goals (spec §2 modes).
// Every stage's reference solution is replayed by tools/validate-content.mjs.

import {
  archSlideBell, archPopUp, archPadBoost, archFanPush, archMagnetLift,
  archDemolition, archAirShow, archChain, sWait,
  M_WALL_L, M_WALL_L2, M_FLOOR,
} from './archetypes.js';
import { sPlace, sTrigger, ledge, wall, stack, crateRow, gBell, gZone, gTopple, gAir, gSpeed, gDistance } from './schema.js';

const PAR = (ticks, score, star3) => ({ ticks, score, star3 });

export const JOURNEY = [
  // ---- Chapter 1: First Sparks (piston & pad) ----
  archSlideBell({
    id: 'j01', name: 'Wake the Dummy', chapter: 1, difficulty: 1, theme: 'brassworks',
    mechanics: ['piston'], bellX: 1.2, aimDy: 0.25, minSpeed: 1.5,
    par: PAR(300, 720, 930),
    intro: 'Mount the Wallop Piston and give the dummy a friendly shove into the bell.',
  }),
  archSlideBell({
    id: 'j02', name: 'Far Side Chime', chapter: 1, difficulty: 1, theme: 'brassworks',
    mechanics: ['piston'], bellX: 2.9, aimDy: 0.3, minSpeed: 1.5, distBonus: 4,
    par: PAR(420, 890, 1150),
    intro: 'The bell is farther now. Aim a touch higher to keep the slide alive.',
  }),
  archPadBoost({
    id: 'j03', name: 'Boing Debut', chapter: 1, difficulty: 1, theme: 'brassworks',
    mechanics: ['piston', 'pad'], padX: -1.0, aimDy: 0.3, bell: { x: 5.0, y: 0.35, r: 0.38, minSpeed: 1.4 },
    par: PAR(720, 750, 970),
    intro: 'A Boing Pad on the floor super-charges anything that skids across it.',
  }),
  archPopUp({
    id: 'j04', name: 'Sky Pop', chapter: 1, difficulty: 1, theme: 'brassworks',
    mechanics: ['piston'], aim: [0, 1], bell: { x: -3, y: 2.55, r: 0.42, minSpeed: 1.2 }, airBonus: 60,
    par: PAR(240, 920, 1200),
    intro: 'Some mounts sit on the floor and fire straight up. Ring the hanging bell on the way.',
  }),
  archSlideBell({
    id: 'j05', name: 'Long Haul', chapter: 1, difficulty: 2, theme: 'brassworks',
    mechanics: ['piston'], bellX: 5.0, aimDy: 0.3, minSpeed: 1.4, distBonus: 7,
    par: PAR(600, 900, 1170),
    intro: 'Maximum slide. Commit to the full send.',
  }),
  archDemolition({
    id: 'j06', name: 'Crate Crash', chapter: 1, difficulty: 2, theme: 'brassworks',
    mechanics: ['piston'], useWeight: false, aimDy: 0.3, count: 2,
    crates: [{ kind: 'crate', x: 1.6, y: 0 }, { kind: 'crate', x: 2.1, y: 0 }],
    par: PAR(180, 700, 910),
    intro: 'The dummy is excellent at crashing into things. Topple both crates.',
  }),
  archPopUp({
    id: 'j07', name: 'Perch Practice', chapter: 1, difficulty: 2, theme: 'brassworks',
    mechanics: ['piston'], aim: [0.7, 0.7], targetZone: { x: 2.0, y: 0.55, r: 0.65 }, holdTicks: 45,
    par: PAR(1020, 830, 1070),
    intro: 'Lob the dummy so it lands inside the chalk circle and stays there.',
  }),
  archChain({
    id: 'j08', name: 'Mastery: Over the Top', chapter: 1, difficulty: 2, theme: 'brassworks',
    mechanics: ['piston'],
    mounts: [{ ...M_FLOOR }],
    extraStatics: [wall(0.3, 0, 1.5)],
    bells: [{ x: 5.0, y: 0.35, r: 0.4, minSpeed: 0.9 }],
    goalDefs: [gBell(0, 0.9, true), gAir(60, false)],
    toolCounts: { piston: 1 },
    plays: [sPlace('piston', M_FLOOR.x, M_FLOOR.y, 0.35, 1, M_FLOOR.id), sTrigger()],
    par: PAR(660, 1000, 1300),
    intro: 'Mastery: arc clean over the divider and bowl into the bell beyond.',
  }),

  // ---- Chapter 2: Moving Air (fan) ----
  archFanPush({
    id: 'j09', name: 'Gentle Breeze', chapter: 2, difficulty: 2, theme: 'tidepool',
    mechanics: ['fan'], fanBack: 0.8, targetZone: { x: 1.5, y: 0.5, r: 0.75 }, holdTicks: 45,
    par: PAR(1140, 760, 980),
    intro: 'The Gust Fan nudges whatever sits in its cone. Blow the dummy into the circle.',
  }),
  archFanPush({
    id: 'j10', name: 'Tailwind Chime', chapter: 2, difficulty: 2, theme: 'tidepool',
    mechanics: ['fan'], fanBack: 2.2, bell: { x: 3.6, y: 0.35, r: 0.4, minSpeed: 0.85 },
    par: PAR(600, 720, 940),
    intro: 'Stand back and let a long gust carry the dummy all the way to the bell.',
  }),
  archChain({
    id: 'j11', name: 'Boosted Breeze', chapter: 2, difficulty: 2, theme: 'tidepool',
    mechanics: ['fan', 'pad'],
    goalDefs: [gZone(4.3, 0.5, 0.8, 45, true)],
    zones: [{ x: 4.3, y: 0.5, r: 0.8 }],
    toolCounts: { fan: 1, pad: 1 },
    plays: [sPlace('pad', 0.2, 0.1), sPlace('fan', -4.2, 0.7, 1, 0.08), sTrigger()],
    par: PAR(600, 730, 940),
    intro: 'A pad mid-gust turns a gentle push into a proper glide.',
  }),
  archAirShow({
    id: 'j12', name: 'Hang Time', chapter: 2, difficulty: 2, theme: 'tidepool',
    mechanics: ['piston'], airTicks: 100, aim: [0, 1],
    par: PAR(360, 830, 1070),
    intro: 'Keep the dummy airborne for a combined hundred ticks. Straight up works wonders.',
  }),
  archFanPush({
    id: 'j13', name: 'Off the Shelf', chapter: 2, difficulty: 3, theme: 'tidepool',
    mechanics: ['fan'], dummy: { x: 1.2, y: 1.5 }, ledge: [0.2, 2.2, 1.5],
    fanX: -0.2, fanY: 1.9, fanDir: [1, -0.05], targetZone: { x: 4.3, y: 0.5, r: 0.85 }, holdTicks: 45,
    par: PAR(540, 750, 970),
    intro: 'The dummy is shelved. Blow it off the edge and across the floor.',
  }),
  archFanPush({
    id: 'j14', name: 'Crate Sweeper', chapter: 2, difficulty: 3, theme: 'tidepool',
    mechanics: ['fan'], fanBack: 1.2, crates: crateRow(1.4, 2, 0.45), toppleGoal: 2,
    par: PAR(180, 700, 900),
    intro: 'Weaponize the breeze: the dummy becomes a very soft bowling ball.',
  }),
  archFanPush({
    id: 'j15', name: 'Precision Gust', chapter: 2, difficulty: 3, theme: 'tidepool',
    mechanics: ['fan'], fanBack: 1.4, targetZone: { x: 3.2, y: 0.5, r: 0.65 }, holdTicks: 45,
    par: PAR(1020, 750, 970),
    intro: 'A shorter gust, a smaller circle. Distance is your throttle.',
  }),
  archChain({
    id: 'j16', name: 'Mastery: Mid-Air Assist', chapter: 2, difficulty: 3, theme: 'tidepool',
    mechanics: ['piston', 'fan'],
    mounts: [{ ...M_FLOOR }],
    bells: [{ x: 4.4, y: 0.35, r: 0.42, minSpeed: 1.2 }],
    goalDefs: [gBell(0, 1.2, true), gAir(80, false)],
    toolCounts: { piston: 1, fan: 1 },
    plays: [
      sPlace('fan', 0.2, 2.6, 1, 0.25),
      sPlace('piston', M_FLOOR.x, M_FLOOR.y, 0.45, 1, M_FLOOR.id),
      sTrigger('piston'),
      sWait(55),
      sTrigger('fan'),
    ],
    par: PAR(420, 980, 1270),
    intro: 'Mastery: launch first, then catch the dummy mid-arc with a gust. Timing is everything.',
  }),

  // ---- Chapter 3: Heavy Metal (weight) ----
  archDemolition({
    id: 'j17', name: 'Anvil Hello', chapter: 3, difficulty: 3, theme: 'emberworks',
    mechanics: ['weight'], useWeight: true, count: 2,
    crates: stack(3, 2), dropX: 3.1,
    par: PAR(1440, 770, 1000),
    intro: 'The Thumper Weight hangs where you place it. Drop it on the stack.',
  }),
  archDemolition({
    id: 'j18', name: 'Twin Towers', chapter: 3, difficulty: 3, theme: 'emberworks',
    mechanics: ['weight'], useWeight: true, count: 4,
    crates: [...stack(2.7, 2), ...stack(3.3, 2)], dropX: 3.0, dropY: 3.6,
    par: PAR(240, 700, 900),
    intro: 'Two towers, one anvil, dropped right between them.',
  }),
  archChain({
    id: 'j19', name: 'Two Birds', chapter: 3, difficulty: 3, theme: 'emberworks',
    mechanics: ['weight', 'piston'],
    mounts: [{ ...M_FLOOR }],
    zones: [{ x: 2.8, y: 0.5, r: 0.7 }],
    props: stack(-4.6, 2),
    goalDefs: [gZone(2.8, 0.5, 0.7, 45, true), gTopple(2, false)],
    toolCounts: { piston: 1, weight: 1 },
    plays: [
      sPlace('piston', M_FLOOR.x, M_FLOOR.y, 0.55, 1, M_FLOOR.id),
      sTrigger('piston'),
      sPlace('weight', -4.6, 3.2),
      sTrigger('weight'),
    ],
    par: PAR(1020, 850, 1100),
    intro: 'Lob the dummy into the circle, then flatten the stack for the bonus.',
  }),
  archChain({
    id: 'j20', name: 'Demolition Row', chapter: 3, difficulty: 3, theme: 'emberworks',
    mechanics: ['weight', 'piston'],
    mounts: [{ ...M_WALL_L }],
    props: crateRow(1.8, 4, 0.45),
    goalDefs: [gTopple(4, true)],
    toolCounts: { weight: 1, piston: 1 },
    plays: [
      sPlace('weight', 2.4, 3.4),
      sTrigger(),
      sPlace('piston', M_WALL_L.x, M_WALL_L.y, 1, 0.3, M_WALL_L.id),
      sTrigger('piston'),
    ],
    par: PAR(180, 780, 1010),
    intro: 'Soften the row with the anvil, then finish with a slide.',
  }),
  archChain({
    id: 'j21', name: 'Shelf Clearing', chapter: 3, difficulty: 4, theme: 'emberworks',
    mechanics: ['weight'],
    extraStatics: [ledge(2.2, 4.2, 1.4)],
    props: [...stack(2.8, 2, 1.4), { kind: 'crate', x: 3.6, y: 1.4 }],
    goalDefs: [gTopple(2, true)],
    toolCounts: { weight: 1 },
    plays: [sPlace('weight', 2.9, 3.6), sTrigger('weight')],
    par: PAR(840, 730, 950),
    intro: 'Crates on the high shelf. Gravity does the paperwork.',
  }),
  archChain({
    id: 'j22', name: 'Ball Boycott', chapter: 3, difficulty: 4, theme: 'emberworks',
    mechanics: ['weight'],
    props: [...stack(2.4, 2), ...stack(3.0, 2), ...stack(3.6, 2)],
    goalDefs: [gTopple(5, true)],
    toolCounts: { weight: 1 },
    plays: [sPlace('weight', 2.9, 3.6), sTrigger('weight')],
    par: PAR(1380, 770, 1000),
    intro: 'One anvil, three towers. Aim for the keystone and start a chain reaction.',
  }),
  archChain({
    id: 'j23', name: 'Fortress Gate', chapter: 3, difficulty: 4, theme: 'emberworks',
    mechanics: ['weight', 'piston'],
    mounts: [{ ...M_FLOOR }],
    props: [...stack(2.2, 2), ...stack(2.7, 2)],
    bells: [{ x: 3.3, y: 0.35, r: 0.42, minSpeed: 0.9 }],
    goalDefs: [gBell(0, 0.9, true), gTopple(2, false)],
    toolCounts: { weight: 1, piston: 1, fan: 1 },
    plays: [
      sPlace('fan', 0.8, 0.8, 1, 0.05),
      sPlace('piston', M_FLOOR.x, M_FLOOR.y, 0.35, 1, M_FLOOR.id),
      sTrigger('piston'),
      sWait(100),
      sTrigger('fan'),
    ],
    par: PAR(480, 1080, 1390),
    intro: 'The crate fort guards the bell. Charge through it — anvils optional.',
  }),
  archChain({
    id: 'j24', name: 'Mastery: Anvil Rain', chapter: 3, difficulty: 4, theme: 'emberworks',
    mechanics: ['weight', 'piston'],
    mounts: [{ ...M_FLOOR }],
    props: stack(4.0, 2),
    bells: [{ x: 2.0, y: 0.35, r: 0.42, minSpeed: 0.9 }],
    goalDefs: [gBell(0, 0.9, true), gTopple(2, false), gAir(90, false)],
    toolCounts: { piston: 1, weight: 1 },
    plays: [
      sPlace('weight', 4.0, 2.6),
      sTrigger('weight'),
      sPlace('piston', M_FLOOR.x, M_FLOOR.y, 0.35, 1, M_FLOOR.id),
      sTrigger('piston'),
    ],
    par: PAR(1860, 1250, 1620),
    intro: 'Mastery: the anvil clears the far stack while the dummy rings the near bell.',
  }),

  // ---- Chapter 4: Attractive Forces (magnet) ----
  archMagnetLift({
    id: 'j25', name: 'Up We Go', chapter: 4, difficulty: 4, theme: 'nocturne',
    mechanics: ['magnet'], magnetY: 2.8, bell: { x: -3, y: 2.55, r: 0.42, minSpeed: 1.0 },
    par: PAR(300, 750, 970),
    intro: 'The Snatch Magnet yanks plush upward. Ring the bell on the way.',
  }),
  archMagnetLift({
    id: 'j26', name: 'Sky Hook', chapter: 4, difficulty: 4, theme: 'nocturne',
    mechanics: ['magnet'], magnetY: 3.0, airGoal: 90,
    par: PAR(360, 830, 1070),
    intro: 'Hold the dummy aloft. Every floating tick counts.',
  }),
  archMagnetLift({
    id: 'j27', name: 'Over the Wall', chapter: 4, difficulty: 4, theme: 'nocturne',
    mechanics: ['magnet'], dummy: { x: -1.5, y: 0 }, wallSeg: [0, 0, 2.1], magnetX: 1.2, magnetY: 3.6,
    targetZone: { x: 2.0, y: 0.5, r: 0.85 }, holdTicks: 45,
    par: PAR(1260, 920, 1190),
    intro: 'A tall divider blocks the floor. Go over it.',
  }),
  archChain({
    id: 'j28', name: 'Mind the Gap', chapter: 4, difficulty: 4, theme: 'nocturne',
    mechanics: ['magnet'], dummy: { x: -1.0, y: 0 },
    extraStatics: [
      [-6, 0, 0.3, 0, 'WOOD'], [1.3, 0, 6, 0, 'WOOD'],
      [0.3, 0, 0.3, -1.2, 'WOOD'], [1.3, -1.2, 1.3, 0, 'WOOD'], [0.3, -1.2, 1.3, -1.2, 'WOOD'],
      wall(-6, 0, 7), wall(6, 0, 7),
    ],
    noArena: true,
    zones: [{ x: 1.9, y: 0.5, r: 0.75 }],
    goalDefs: [gZone(1.9, 0.5, 0.75, 45, true)],
    toolCounts: { magnet: 1 },
    plays: [sPlace('magnet', 1.8, 3.0), sTrigger('magnet')],
    par: PAR(1320, 910, 1180),
    intro: 'A pit yawns between the dummy and the circle. Float across.',
  }),
  archChain({
    id: 'j29', name: 'Mastery: Sky Crane', chapter: 4, difficulty: 4, theme: 'nocturne',
    mechanics: ['magnet', 'fan'],
    zones: [{ x: 2.0, y: 0.5, r: 0.9 }],
    goalDefs: [gZone(2.0, 0.5, 0.9, 45, true), gAir(70, false)],
    toolCounts: { magnet: 1, fan: 1 },
    plays: [
      sPlace('magnet', -2.2, 3.2),
      sPlace('fan', -3.9, 1.3, 1, 0.3),
      sTrigger('magnet'),
      sWait(190),
      sTrigger('fan'),
    ],
    par: PAR(960, 1090, 1410),
    intro: 'Mastery: hoist with the magnet, then blow the floating dummy across the shop.',
  }),

  // ---- Chapter 5: Grand Mayhem (everything) ----
  archChain({
    id: 'j30', name: 'Assembly Line', chapter: 5, difficulty: 5, theme: 'verdant',
    mechanics: ['piston', 'fan'],
    mounts: [{ ...M_WALL_L }],
    props: crateRow(2.0, 3, 0.45),
    bells: [{ x: 4.8, y: 0.35, r: 0.4, minSpeed: 1.2 }],
    goalDefs: [gTopple(3, true), gBell(0, 1.2, false)],
    toolCounts: { piston: 1, fan: 1 },
    plays: [
      sPlace('fan', -4.4, 0.7, 1, 0.08),
      sPlace('piston', M_WALL_L.x, M_WALL_L.y, 1, 0.3, M_WALL_L.id),
      sTrigger('piston'),
      sWait(30),
      sTrigger('fan'),
    ],
    par: PAR(540, 730, 940),
    intro: 'Punch, then tailwind. Clear the crates and ring the bell in one flow.',
  }),
  archChain({
    id: 'j31', name: 'The Long Way Up', chapter: 5, difficulty: 5, theme: 'verdant',
    mechanics: ['piston', 'magnet'],
    mounts: [{ ...M_FLOOR }],
    bells: [{ x: -3.2, y: 3.6, r: 0.42, minSpeed: 1.0 }],
    goalDefs: [gBell(0, 1.0, true), gAir(140, false)],
    toolCounts: { piston: 1, magnet: 1 },
    plays: [
      sPlace('magnet', -3.2, 4.6),
      sPlace('piston', M_FLOOR.x, M_FLOOR.y, 0, 1, M_FLOOR.id),
      sTrigger('piston'),
      sWait(80),
      sTrigger('magnet'),
    ],
    par: PAR(240, 770, 1000),
    intro: 'Pop up, then let the magnet carry the climb to the high bell.',
  }),
  archChain({
    id: 'j32', name: 'Mastery: Full Workshop', chapter: 5, difficulty: 5, theme: 'verdant',
    mechanics: ['piston', 'pad', 'fan', 'weight'],
    mounts: [{ ...M_FLOOR }],
    extraStatics: [wall(1.0, 0, 1.8)],
    props: stack(3.4, 2),
    bells: [{ x: 5.0, y: 0.35, r: 0.4, minSpeed: 1.2 }],
    goalDefs: [gBell(0, 1.2, true), gTopple(2, false), gAir(90, false)],
    toolCounts: { piston: 1, pad: 1, fan: 1, weight: 1 },
    plays: [
      sPlace('pad', 2.0, 0.1),
      sPlace('fan', -1.8, 3.0, 1, 0.05),
      sPlace('weight', 3.4, 3.4),
      sPlace('piston', M_FLOOR.x, M_FLOOR.y, 0.5, 1, M_FLOOR.id),
      sTrigger('piston'),
      sWait(50),
      sTrigger('fan'),
      sWait(240),
      sTrigger('weight'),
    ],
    par: PAR(420, 1180, 1520),
    intro: 'Mastery: every tool on the bench. Arc, gust, demolish, chime.',
  }),

  // ---- Chapter 6: Inventor's Gauntlet (expert) ----
  archChain({
    id: 'j33', name: 'Gauntlet: Narrow Door', chapter: 6, difficulty: 5, theme: 'midnight',
    mechanics: ['piston'],
    mounts: [{ ...M_FLOOR }],
    extraStatics: [wall(0.8, 0, 2.4)],
    zones: [{ x: 2.9, y: 0.5, r: 0.6 }],
    goalDefs: [gZone(2.9, 0.5, 0.6, 45, true)],
    toolCounts: { piston: 1 },
    plays: [sPlace('piston', M_FLOOR.x, M_FLOOR.y, 0.55, 1, M_FLOOR.id), sTrigger()],
    par: PAR(1080, 860, 1110),
    intro: 'Clear the tall wall and land in the small circle beyond.',
  }),
  archChain({
    id: 'j34', name: 'Gauntlet: Air Mail', chapter: 6, difficulty: 5, theme: 'midnight',
    mechanics: ['piston', 'fan'],
    mounts: [{ ...M_FLOOR }],
    zones: [{ x: 4.6, y: 0.5, r: 0.6 }],
    goalDefs: [gZone(4.6, 0.5, 0.6, 45, true), gAir(110, false)],
    toolCounts: { piston: 1, fan: 1 },
    plays: [
      sPlace('fan', 0.6, 2.8, 1, 0.15),
      sPlace('piston', M_FLOOR.x, M_FLOOR.y, 0.35, 1, M_FLOOR.id),
      sTrigger('piston'),
      sWait(60),
      sTrigger('fan'),
    ],
    par: PAR(720, 1010, 1300),
    intro: 'A mid-flight gust is the only way this parcel reaches its circle.',
  }),
  archChain({
    id: 'j35', name: 'Gauntlet: Castle Siege', chapter: 6, difficulty: 5, theme: 'midnight',
    mechanics: ['weight', 'fan'],
    props: [...stack(2.2, 2), ...stack(2.7, 3)],
    bells: [{ x: 2.45, y: 0.35, r: 0.38, minSpeed: 1.0 }],
    goalDefs: [gTopple(5, true), gBell(0, 1.0, false)],
    toolCounts: { weight: 1, fan: 1 },
    plays: [
      sPlace('weight', 2.45, 3.6),
      sTrigger(),
      sPlace('fan', -4.0, 0.7, 1, 0.1),
      sTrigger(),
    ],
    par: PAR(240, 810, 1050),
    intro: 'Five crates guard their bell. Topple the castle, then ring it anyway.',
  }),
  archChain({
    id: 'j36', name: 'Gauntlet: Orbit', chapter: 6, difficulty: 5, theme: 'midnight',
    mechanics: ['magnet', 'piston'],
    mounts: [{ ...M_FLOOR }],
    extraStatics: [wall(0.5, 0, 3.0)],
    zones: [{ x: 3.4, y: 0.5, r: 0.75 }],
    goalDefs: [gZone(3.4, 0.5, 0.75, 45, true), gAir(120, false)],
    toolCounts: { magnet: 1, piston: 1 },
    plays: [
      sPlace('magnet', 1.4, 4.2),
      sPlace('piston', M_FLOOR.x, M_FLOOR.y, 0.25, 1, M_FLOOR.id),
      sTrigger('piston'),
      sWait(65),
      sTrigger('magnet'),
    ],
    par: PAR(900, 1110, 1440),
    intro: 'A three-metre wall says no. The magnet disagrees.',
  }),
  archChain({
    id: 'j37', name: 'Gauntlet: Rush Order', chapter: 6, difficulty: 5, theme: 'midnight',
    mechanics: ['piston', 'pad'],
    mounts: [{ ...M_WALL_L }],
    bells: [{ x: 5.0, y: 0.35, r: 0.4, minSpeed: 1.4 }],
    goalDefs: [gBell(0, 1.4, true), gSpeed(11, false)],
    toolCounts: { piston: 1, pad: 1 },
    plays: [
      sPlace('pad', -0.6, 0.1),
      sPlace('piston', M_WALL_L.x, M_WALL_L.y, 1, 0.28, M_WALL_L.id),
      sTrigger(),
    ],
    challenge: { timeLimitTicks: 2400 },
    par: PAR(540, 900, 1170),
    intro: 'The client is waiting. Boosted slide, far bell, no dawdling.',
  }),
  archChain({
    id: 'j38', name: 'Gauntlet: Skyhook Delivery', chapter: 6, difficulty: 5, theme: 'midnight',
    mechanics: ['weight', 'magnet'], dummy: { x: 3.2, y: 2.2 },
    extraStatics: [ledge(2.6, 3.8, 2.2)],
    props: stack(-4.4, 2),
    zones: [{ x: 0.0, y: 0.5, r: 0.75 }],
    goalDefs: [gZone(0.0, 0.5, 0.75, 45, true), gTopple(2, false)],
    toolCounts: { magnet: 1, weight: 1 },
    plays: [
      sPlace('magnet', 0.0, 3.6),
      sTrigger('magnet'),
      sPlace('weight', -4.4, 3.2),
      sTrigger('weight'),
    ],
    par: PAR(720, 1070, 1390),
    intro: 'Pluck the dummy off its shelf and deliver it to the circle, shelves to spare.',
  }),
  archChain({
    id: 'j39', name: 'Gauntlet: Triple Crown', chapter: 6, difficulty: 5, theme: 'midnight',
    mechanics: ['piston', 'pad', 'weight'],
    mounts: [{ ...M_FLOOR }],
    props: [...stack(3.0, 2), ...stack(4.0, 2)],
    bells: [{ x: 5.1, y: 0.35, r: 0.4, minSpeed: 1.2 }],
    goalDefs: [gTopple(3, true), gBell(0, 1.2, false), gAir(80, false)],
    toolCounts: { weight: 1, piston: 1, pad: 1 },
    plays: [
      sPlace('pad', -3, 0.1),
      sPlace('weight', 3.4, 3.6),
      sPlace('piston', M_FLOOR.x, M_FLOOR.y, 0.4, 1, M_FLOOR.id),
      sTrigger('piston'),
      sWait(200),
      sTrigger('weight'),
    ],
    par: PAR(540, 1000, 1290),
    intro: 'Demolish both stacks, then fly the coop to the bell.',
  }),
  archChain({
    id: 'j40', name: 'Gauntlet: Workshop Mayhem', chapter: 6, difficulty: 5, theme: 'midnight',
    mechanics: ['piston', 'pad', 'fan', 'magnet', 'weight'],
    mounts: [{ ...M_WALL_L }],
    props: [...stack(4.6, 2), ...stack(5.2, 2)],
    bells: [{ x: 3.0, y: 0.35, r: 0.42, minSpeed: 0.9 }],
    zones: [],
    goalDefs: [gBell(0, 0.9, true), gTopple(4, false), gAir(40, false)],
    toolCounts: { piston: 1, pad: 1, fan: 1, magnet: 1, weight: 1 },
    plays: [
      sPlace('weight', 4.9, 3.4),
      sTrigger('weight'),
      sPlace('piston', M_WALL_L.x, M_WALL_L.y, 1, 0.3, M_WALL_L.id),
      sTrigger('piston'),
    ],
    par: PAR(2160, 1420, 1830),
    intro: 'The final commission. Every tool on the bench — but the bell only cares about results.',
  }),
];

// ---- Challenge mode: constrained goals --------------------------------------
export const CHALLENGES = [
  archSlideBell({
    id: 'c1', name: 'One Punch', chapter: 0, difficulty: 3, theme: 'brassworks',
    mechanics: ['piston'], bellX: 2.9, aimDy: 0.3, minSpeed: 1.4,
    challenge: { moveLimit: 1 },
    par: PAR(420, 720, 930),
    intro: 'Challenge: exactly one tool use. Make it count.',
  }),
  archPadBoost({
    id: 'c2', name: 'Speed Freak', chapter: 0, difficulty: 3, theme: 'brassworks',
    mechanics: ['piston', 'pad'], padX: -1.0, aimDy: 0.3, speedGoal: 11,
    par: PAR(240, 710, 920),
    intro: 'Challenge: reach 11 m/s. The pad is your accelerator.',
  }),
  archFanPush({
    id: 'c3', name: 'Clockwork', chapter: 0, difficulty: 3, theme: 'tidepool',
    mechanics: ['fan'], fanBack: 1.6, targetZone: { x: 2.2, y: 0.5, r: 0.8 }, holdTicks: 45,
    challenge: { timeLimitTicks: 1800 },
    par: PAR(480, 710, 920),
    intro: 'Challenge: fifteen simulated seconds. Place fast, trigger faster.',
  }),
  archMagnetLift({
    id: 'c4', name: 'Minimalist', chapter: 0, difficulty: 3, theme: 'nocturne',
    mechanics: ['magnet'], magnetY: 2.8, bell: { x: -3, y: 2.55, r: 0.42, minSpeed: 1.0 },
    challenge: { moveLimit: 1 },
    par: PAR(300, 750, 970),
    intro: 'Challenge: one magnet, one bell, no margin for fiddling.',
  }),
  archDemolition({
    id: 'c5', name: 'Demolition Derby', chapter: 0, difficulty: 4, theme: 'emberworks',
    mechanics: ['weight'], useWeight: true, count: 4,
    crates: [...stack(2.7, 2), ...stack(3.3, 2)], dropX: 3.0, dropY: 3.6,
    challenge: { moveLimit: 1 },
    par: PAR(240, 700, 900),
    intro: 'Challenge: four crates, one anvil, one drop.',
  }),
  archAirShow({
    id: 'c6', name: 'Air Marshal', chapter: 0, difficulty: 4, theme: 'tidepool',
    mechanics: ['piston', 'pad'], airTicks: 180, aim: [0, 1], withPad: true, padX: -3,
    par: PAR(480, 860, 1120),
    intro: 'Challenge: 180 airborne ticks. Launch, bounce, float.',
  }),
  archChain({
    id: 'c7', name: 'Thread the Needle', chapter: 0, difficulty: 5, theme: 'midnight',
    mechanics: ['piston'],
    mounts: [{ ...M_FLOOR }],
    extraStatics: [wall(0.6, 0, 2.0)],
    zones: [{ x: 2.9, y: 0.5, r: 0.5 }],
    goalDefs: [gZone(2.9, 0.5, 0.5, 45, true)],
    toolCounts: { piston: 1 },
    plays: [sPlace('piston', M_FLOOR.x, M_FLOOR.y, 0.55, 1, M_FLOOR.id), sTrigger()],
    challenge: { moveLimit: 1 },
    par: PAR(1080, 860, 1110),
    intro: 'Challenge: one launch, a tall wall, a teacup of a landing circle.',
  }),
  archChain({
    id: 'c8', name: 'Grandmaster Shift', chapter: 0, difficulty: 5, theme: 'midnight',
    mechanics: ['piston', 'fan', 'magnet'],
    mounts: [{ ...M_FLOOR }],
    bells: [{ x: 4.6, y: 0.35, r: 0.42, minSpeed: 1.2 }],
    goalDefs: [gBell(0, 1.2, true), gAir(120, false)],
    toolCounts: { piston: 1, fan: 1, magnet: 1 },
    plays: [
      sPlace('magnet', 0.8, 4.2),
      sPlace('fan', 0.2, 2.8, 1, 0.2),
      sPlace('piston', M_FLOOR.x, M_FLOOR.y, 0.4, 1, M_FLOOR.id),
      sTrigger('piston'),
      sWait(60),
      sTrigger('fan'),
      sWait(120),
      sTrigger('magnet'),
    ],
    challenge: { moveLimit: 3, timeLimitTicks: 4200 },
    par: PAR(480, 990, 1280),
    intro: 'Challenge: three moves on the clock. Launch, lift, deliver.',
  }),
];

export function journeyById(id) {
  return JOURNEY.find(l => l.id === id) || CHALLENGES.find(l => l.id === id) || null;
}
